export default function Terms() {
  return (
    <main className="max-w-2xl mx-auto px-4 py-12">
      <h1 className="text-2xl font-black mb-4">Terms of Service</h1>
      <p className="text-sm text-zinc-600 leading-relaxed">
        The predictions generated by CollegeAchiver are simulators generated from past round analytics of official JoSAA/CSAB sheets. Actual year seat allocations can vary based on student preferences and board cutoffs.
      </p>
    </main>
  );
}